services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
        - 8000:8000
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
      ENVIRONMENT: test
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build: ./frontend
    ports:
    - "5173:80"
    depends_on:
      backend:
        condition: service_healthy
