services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
        - '6379:6379'
    command: >
      redis-server
      --appendonly yes
      --requirepass mysecretpassword
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "mysecretpassword", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
        - 8000:8000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: mysecretpassword
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
      ENVIRONMENT: test
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 30
      SECRET_KEY: 6a36ebfd88dbdc80310f3c463a23a79f78dca4055b8e76ffd83bb4206462aa21
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build: ./frontend
    ports:
    - "5173:80"
    environment:
      VITE_API_URL: http://localhost:8000/api
    depends_on:
      backend:
        condition: service_healthy
