services:
  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/backend/app
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data