services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
        image: redis:latest
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        command: >
          redis-server
          --appendonly yes
          --requirepass mysecretpassword
        restart: unless-stopped

volumes:
  pgdata:
  redis-data:
        driver: local
