"""add_transaction_type_and_enforce_positive_amount

Revision ID: 13beb75cbeba
Revises: e5de371b939d
Create Date: 2026-02-11 12:04:56.732752

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "13beb75cbeba"
down_revision: Union[str, Sequence[str], None] = "e5de371b939d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("INCOME", "EXPENSE", "TRANSFER", name="transactiontype").create(
        op.get_bind()
    )
    op.add_column(
        "transactions",
        sa.Column(
            "transaction_type",
            sa.Enum("INCOME", "EXPENSE", "TRANSFER", name="transactiontype"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "transaction_type")
    sa.Enum("INCOME", "EXPENSE", "TRANSFER", name="transactiontype").drop(op.get_bind())
    # ### end Alembic commands ###
