"""add_category_user_relation

Revision ID: 273d79f5c7a6
Revises: bf03007ed6a4
Create Date: 2026-07-26 11:56:39.352544

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "273d79f5c7a6"
down_revision: Union[str, Sequence[str], None] = "bf03007ed6a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=False)
    op.create_unique_constraint(
        "unique_user_category_name", "categories", ["user_id", "name"]
    )
    op.create_foreign_key(None, "categories", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_constraint("unique_user_category_name", "categories", type_="unique")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.drop_column("categories", "user_id")
    # ### end Alembic commands ###
