"""add_categories_table

Revision ID: 3bfd45972055
Revises: 13beb75cbeba
Create Date: 2026-02-11 22:45:03.284968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "3bfd45972055"
down_revision: Union[str, Sequence[str], None] = "13beb75cbeba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "allowed_type",
            postgresql.ENUM(
                "INCOME", "EXPENSE", name="transactiontype", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.add_column("transactions", sa.Column("category_id", sa.Integer(), nullable=True))
    op.drop_index(op.f("ix_transactions_category"), table_name="transactions")
    op.create_foreign_key(None, "transactions", "categories", ["category_id"], ["id"])
    op.drop_column("transactions", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.create_index(
        op.f("ix_transactions_category"), "transactions", ["category"], unique=False
    )
    op.drop_column("transactions", "category_id")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
