"""add transaction user relation

Revision ID: 581ad9eea5fd
Revises: dc37fe583040
Create Date: 2026-07-25 10:28:16.231765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "581ad9eea5fd"
down_revision: Union[str, Sequence[str], None] = "dc37fe583040"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "transactions_user_id_fkey", "transactions", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("transactions_user_id_fkey", "transactions", type_="foreignkey")
    op.drop_column("transactions", "user_id")
    # ### end Alembic commands ###
