"""make user_id and category_id non-nullable

Revision ID: bf03007ed6a4
Revises: 581ad9eea5fd
Create Date: 2026-07-25 10:38:12.330251

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf03007ed6a4"
down_revision: Union[str, Sequence[str], None] = "581ad9eea5fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions", "category_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column("transactions", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transactions", "user_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "transactions", "category_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
