"""add uuid columns to Category and Transaction

Revision ID: d84405bd66ad
Revises: efa7812c3ec3
Create Date: 2026-04-07 13:53:55.457265

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d84405bd66ad"
down_revision: Union[str, Sequence[str], None] = "efa7812c3ec3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column(
            "category_uuid",
            sa.Uuid(),
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "transaction_uuid",
            sa.Uuid(),
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
    )
    op.add_column("transactions", sa.Column("category_uuid", sa.Uuid(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "category_uuid")
    op.drop_column("transactions", "transaction_uuid")
    op.drop_column("categories", "category_uuid")

    # ### end Alembic commands ###
