name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy started
        run: echo "👀 Deployment started"

      - name: Deploy finished
        run: echo "🎉 App deployed"
